sudo: required
dist: trusty
branches:
  only:
    - develop
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
env:
  - ELECTRON_CACHE=$HOME/.cache/electron
  - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
# https://www.electron.build/multi-platform-build
matrix:
  include:
    - os: osx
      osx_image: xcode9.4
      language: node_js
      node_js: "10"
    - os: linux
      services: docker
cache:
  directories:
    - node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder
before_cache:
  - 'pwd && ls -als'
  - 'npm --version'
  - 'node --version'
  - 'rm -rf $HOME/.cache/electron-builder/wine'
before_install:
  - 'pwd && ls -als'
  - 'npm --version'
  - 'node --version'
install:
  - 'pwd && ls -als'
  - 'npm --version'
  - 'node --version'
before_script:
  - 'pwd && ls -als'
  - 'npm --version'
  - 'node --version'
script:
  - 'pwd && ls -als'
  - 'npm --version'
  - 'node --version'
  - |
    if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      docker run --rm \
        --env-file <(env | grep -iE 'DEBUG|NODE_|ELECTRON_|YARN_|NPM_|CI|CIRCLE|TRAVIS|APPVEYOR_|CSC_|_TOKEN|_KEY|AWS_|STRIP|BUILD_') \
        -v ${PWD}:/project \
        -v ~/.cache/electron:/root/.cache/electron \
        -v ~/.cache/electron-builder:/root/.cache/electron-builder \
        electronuserland/builder:wine \
        /bin/bash -c "npm install && npm run build && ls -als dist && npm run electron-pack:prepare && ls -als dist/electron && npm run electron-pack:travis-docker-linux-win && ls -als electron-pack && ls -als electron-pack/linux-unpacked && ls -als electron-pack/win-unpacked"
    else
      npm install && npm run build && ls -als dist && npm run electron-pack:prepare && ls -als dist/electron && npm run electron-pack:travis-mac && ls -als electron-pack && ls -als electron-pack/mac
    fi
after_success:
  - 'pwd && ls -als'
  - 'npm --version'
  - 'node --version'
  - 'ls dist'
  - 'ls -als dist/electron'
  - 'ls -als electron-pack'
after_failure:
  - 'pwd && ls -als'
  - 'npm --version'
  - 'node --version'
deploy:
  provider: releases
  api_key: $GH_TOKEN
  file_glob: true
  file:
    - "electron-pack/**/*.AppImage"
    - "electron-pack/**/*.deb"
    - "electron-pack/**/*.msi"
    - "electron-pack/**/*.nsi"
    - "electron-pack/**/*.exe"
    - "electron-pack/**/*.dmg"
  skip_cleanup: true
  on:
    tags: false
    branches:
      only:
        - develop
